/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppuserRouteRouteImport } from './routes/app/(user)/route'
import { Route as AppOrganizationIdRouteRouteImport } from './routes/app/$organizationId/route'
import { Route as AppuserIndexRouteImport } from './routes/app/(user)/index'
import { Route as AppOrganizationIdIndexRouteImport } from './routes/app/$organizationId/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppuserAdminRouteRouteImport } from './routes/app/(user)/admin/route'
import { Route as AppOrganizationIdPropertyRouteRouteImport } from './routes/app/$organizationId/property/route'
import { Route as AppuserAdminIndexRouteImport } from './routes/app/(user)/admin/index'
import { Route as AppuserAccountIndexRouteImport } from './routes/app/(user)/account/index'
import { Route as AppOrganizationIdPropertyIndexRouteImport } from './routes/app/$organizationId/property/index'
import { Route as AppOrganizationIdPropertyImportRouteImport } from './routes/app/$organizationId/property/import'
import { Route as AppOrganizationIdPropertyCreateRouteImport } from './routes/app/$organizationId/property/create'
import { Route as AppOrganizationIdPropertyPropertyIdRouteImport } from './routes/app/$organizationId/property/$propertyId'
import { Route as AppuserAdminOrganizationIndexRouteImport } from './routes/app/(user)/admin/organization/index'
import { Route as AppuserAdminOrganizationCreateRouteImport } from './routes/app/(user)/admin/organization/create'
import { Route as AppuserAdminOrganizationIdRouteImport } from './routes/app/(user)/admin/organization/$id'
import { Route as AppOrganizationIdPropertyPropertyIdEditRouteImport } from './routes/app/$organizationId/property/$propertyId/edit'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppuserRouteRoute = AppuserRouteRouteImport.update({
  id: '/(user)',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationIdRouteRoute = AppOrganizationIdRouteRouteImport.update({
  id: '/$organizationId',
  path: '/$organizationId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppuserIndexRoute = AppuserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppuserRouteRoute,
} as any)
const AppOrganizationIdIndexRoute = AppOrganizationIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganizationIdRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppuserAdminRouteRoute = AppuserAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppuserRouteRoute,
} as any)
const AppOrganizationIdPropertyRouteRoute =
  AppOrganizationIdPropertyRouteRouteImport.update({
    id: '/property',
    path: '/property',
    getParentRoute: () => AppOrganizationIdRouteRoute,
  } as any)
const AppuserAdminIndexRoute = AppuserAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppuserAdminRouteRoute,
} as any)
const AppuserAccountIndexRoute = AppuserAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppuserRouteRoute,
} as any)
const AppOrganizationIdPropertyIndexRoute =
  AppOrganizationIdPropertyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationIdPropertyRouteRoute,
  } as any)
const AppOrganizationIdPropertyImportRoute =
  AppOrganizationIdPropertyImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AppOrganizationIdPropertyRouteRoute,
  } as any)
const AppOrganizationIdPropertyCreateRoute =
  AppOrganizationIdPropertyCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppOrganizationIdPropertyRouteRoute,
  } as any)
const AppOrganizationIdPropertyPropertyIdRoute =
  AppOrganizationIdPropertyPropertyIdRouteImport.update({
    id: '/$propertyId',
    path: '/$propertyId',
    getParentRoute: () => AppOrganizationIdPropertyRouteRoute,
  } as any)
const AppuserAdminOrganizationIndexRoute =
  AppuserAdminOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => AppuserAdminRouteRoute,
  } as any)
const AppuserAdminOrganizationCreateRoute =
  AppuserAdminOrganizationCreateRouteImport.update({
    id: '/organization/create',
    path: '/organization/create',
    getParentRoute: () => AppuserAdminRouteRoute,
  } as any)
const AppuserAdminOrganizationIdRoute =
  AppuserAdminOrganizationIdRouteImport.update({
    id: '/organization/$id',
    path: '/organization/$id',
    getParentRoute: () => AppuserAdminRouteRoute,
  } as any)
const AppOrganizationIdPropertyPropertyIdEditRoute =
  AppOrganizationIdPropertyPropertyIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppOrganizationIdPropertyPropertyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppuserRouteRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/app/$organizationId': typeof AppOrganizationIdRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/app/$organizationId/property': typeof AppOrganizationIdPropertyRouteRouteWithChildren
  '/app/admin': typeof AppuserAdminRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$organizationId/': typeof AppOrganizationIdIndexRoute
  '/app/': typeof AppuserIndexRoute
  '/app/$organizationId/property/$propertyId': typeof AppOrganizationIdPropertyPropertyIdRouteWithChildren
  '/app/$organizationId/property/create': typeof AppOrganizationIdPropertyCreateRoute
  '/app/$organizationId/property/import': typeof AppOrganizationIdPropertyImportRoute
  '/app/$organizationId/property/': typeof AppOrganizationIdPropertyIndexRoute
  '/app/account/': typeof AppuserAccountIndexRoute
  '/app/admin/': typeof AppuserAdminIndexRoute
  '/app/$organizationId/property/$propertyId/edit': typeof AppOrganizationIdPropertyPropertyIdEditRoute
  '/app/admin/organization/$id': typeof AppuserAdminOrganizationIdRoute
  '/app/admin/organization/create': typeof AppuserAdminOrganizationCreateRoute
  '/app/admin/organization/': typeof AppuserAdminOrganizationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppuserIndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$organizationId': typeof AppOrganizationIdIndexRoute
  '/app/$organizationId/property/$propertyId': typeof AppOrganizationIdPropertyPropertyIdRouteWithChildren
  '/app/$organizationId/property/create': typeof AppOrganizationIdPropertyCreateRoute
  '/app/$organizationId/property/import': typeof AppOrganizationIdPropertyImportRoute
  '/app/$organizationId/property': typeof AppOrganizationIdPropertyIndexRoute
  '/app/account': typeof AppuserAccountIndexRoute
  '/app/admin': typeof AppuserAdminIndexRoute
  '/app/$organizationId/property/$propertyId/edit': typeof AppOrganizationIdPropertyPropertyIdEditRoute
  '/app/admin/organization/$id': typeof AppuserAdminOrganizationIdRoute
  '/app/admin/organization/create': typeof AppuserAdminOrganizationCreateRoute
  '/app/admin/organization': typeof AppuserAdminOrganizationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/app/$organizationId': typeof AppOrganizationIdRouteRouteWithChildren
  '/app/(user)': typeof AppuserRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/app/$organizationId/property': typeof AppOrganizationIdPropertyRouteRouteWithChildren
  '/app/(user)/admin': typeof AppuserAdminRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$organizationId/': typeof AppOrganizationIdIndexRoute
  '/app/(user)/': typeof AppuserIndexRoute
  '/app/$organizationId/property/$propertyId': typeof AppOrganizationIdPropertyPropertyIdRouteWithChildren
  '/app/$organizationId/property/create': typeof AppOrganizationIdPropertyCreateRoute
  '/app/$organizationId/property/import': typeof AppOrganizationIdPropertyImportRoute
  '/app/$organizationId/property/': typeof AppOrganizationIdPropertyIndexRoute
  '/app/(user)/account/': typeof AppuserAccountIndexRoute
  '/app/(user)/admin/': typeof AppuserAdminIndexRoute
  '/app/$organizationId/property/$propertyId/edit': typeof AppOrganizationIdPropertyPropertyIdEditRoute
  '/app/(user)/admin/organization/$id': typeof AppuserAdminOrganizationIdRoute
  '/app/(user)/admin/organization/create': typeof AppuserAdminOrganizationCreateRoute
  '/app/(user)/admin/organization/': typeof AppuserAdminOrganizationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/llms.txt'
    | '/app/$organizationId'
    | '/sign-in'
    | '/sign-up'
    | '/app/$organizationId/property'
    | '/app/admin'
    | '/api/auth/$'
    | '/app/$organizationId/'
    | '/app/'
    | '/app/$organizationId/property/$propertyId'
    | '/app/$organizationId/property/create'
    | '/app/$organizationId/property/import'
    | '/app/$organizationId/property/'
    | '/app/account/'
    | '/app/admin/'
    | '/app/$organizationId/property/$propertyId/edit'
    | '/app/admin/organization/$id'
    | '/app/admin/organization/create'
    | '/app/admin/organization/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/llms.txt'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
    | '/app/$organizationId'
    | '/app/$organizationId/property/$propertyId'
    | '/app/$organizationId/property/create'
    | '/app/$organizationId/property/import'
    | '/app/$organizationId/property'
    | '/app/account'
    | '/app/admin'
    | '/app/$organizationId/property/$propertyId/edit'
    | '/app/admin/organization/$id'
    | '/app/admin/organization/create'
    | '/app/admin/organization'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/llms.txt'
    | '/app/$organizationId'
    | '/app/(user)'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/app/$organizationId/property'
    | '/app/(user)/admin'
    | '/api/auth/$'
    | '/app/$organizationId/'
    | '/app/(user)/'
    | '/app/$organizationId/property/$propertyId'
    | '/app/$organizationId/property/create'
    | '/app/$organizationId/property/import'
    | '/app/$organizationId/property/'
    | '/app/(user)/account/'
    | '/app/(user)/admin/'
    | '/app/$organizationId/property/$propertyId/edit'
    | '/app/(user)/admin/organization/$id'
    | '/app/(user)/admin/organization/create'
    | '/app/(user)/admin/organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/(user)': {
      id: '/app/(user)'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppuserRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$organizationId': {
      id: '/app/$organizationId'
      path: '/$organizationId'
      fullPath: '/app/$organizationId'
      preLoaderRoute: typeof AppOrganizationIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(user)/': {
      id: '/app/(user)/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppuserIndexRouteImport
      parentRoute: typeof AppuserRouteRoute
    }
    '/app/$organizationId/': {
      id: '/app/$organizationId/'
      path: '/'
      fullPath: '/app/$organizationId/'
      preLoaderRoute: typeof AppOrganizationIdIndexRouteImport
      parentRoute: typeof AppOrganizationIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/(user)/admin': {
      id: '/app/(user)/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppuserAdminRouteRouteImport
      parentRoute: typeof AppuserRouteRoute
    }
    '/app/$organizationId/property': {
      id: '/app/$organizationId/property'
      path: '/property'
      fullPath: '/app/$organizationId/property'
      preLoaderRoute: typeof AppOrganizationIdPropertyRouteRouteImport
      parentRoute: typeof AppOrganizationIdRouteRoute
    }
    '/app/(user)/admin/': {
      id: '/app/(user)/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppuserAdminIndexRouteImport
      parentRoute: typeof AppuserAdminRouteRoute
    }
    '/app/(user)/account/': {
      id: '/app/(user)/account/'
      path: '/account'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AppuserAccountIndexRouteImport
      parentRoute: typeof AppuserRouteRoute
    }
    '/app/$organizationId/property/': {
      id: '/app/$organizationId/property/'
      path: '/'
      fullPath: '/app/$organizationId/property/'
      preLoaderRoute: typeof AppOrganizationIdPropertyIndexRouteImport
      parentRoute: typeof AppOrganizationIdPropertyRouteRoute
    }
    '/app/$organizationId/property/import': {
      id: '/app/$organizationId/property/import'
      path: '/import'
      fullPath: '/app/$organizationId/property/import'
      preLoaderRoute: typeof AppOrganizationIdPropertyImportRouteImport
      parentRoute: typeof AppOrganizationIdPropertyRouteRoute
    }
    '/app/$organizationId/property/create': {
      id: '/app/$organizationId/property/create'
      path: '/create'
      fullPath: '/app/$organizationId/property/create'
      preLoaderRoute: typeof AppOrganizationIdPropertyCreateRouteImport
      parentRoute: typeof AppOrganizationIdPropertyRouteRoute
    }
    '/app/$organizationId/property/$propertyId': {
      id: '/app/$organizationId/property/$propertyId'
      path: '/$propertyId'
      fullPath: '/app/$organizationId/property/$propertyId'
      preLoaderRoute: typeof AppOrganizationIdPropertyPropertyIdRouteImport
      parentRoute: typeof AppOrganizationIdPropertyRouteRoute
    }
    '/app/(user)/admin/organization/': {
      id: '/app/(user)/admin/organization/'
      path: '/organization'
      fullPath: '/app/admin/organization/'
      preLoaderRoute: typeof AppuserAdminOrganizationIndexRouteImport
      parentRoute: typeof AppuserAdminRouteRoute
    }
    '/app/(user)/admin/organization/create': {
      id: '/app/(user)/admin/organization/create'
      path: '/organization/create'
      fullPath: '/app/admin/organization/create'
      preLoaderRoute: typeof AppuserAdminOrganizationCreateRouteImport
      parentRoute: typeof AppuserAdminRouteRoute
    }
    '/app/(user)/admin/organization/$id': {
      id: '/app/(user)/admin/organization/$id'
      path: '/organization/$id'
      fullPath: '/app/admin/organization/$id'
      preLoaderRoute: typeof AppuserAdminOrganizationIdRouteImport
      parentRoute: typeof AppuserAdminRouteRoute
    }
    '/app/$organizationId/property/$propertyId/edit': {
      id: '/app/$organizationId/property/$propertyId/edit'
      path: '/edit'
      fullPath: '/app/$organizationId/property/$propertyId/edit'
      preLoaderRoute: typeof AppOrganizationIdPropertyPropertyIdEditRouteImport
      parentRoute: typeof AppOrganizationIdPropertyPropertyIdRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AppOrganizationIdPropertyPropertyIdRouteChildren {
  AppOrganizationIdPropertyPropertyIdEditRoute: typeof AppOrganizationIdPropertyPropertyIdEditRoute
}

const AppOrganizationIdPropertyPropertyIdRouteChildren: AppOrganizationIdPropertyPropertyIdRouteChildren =
  {
    AppOrganizationIdPropertyPropertyIdEditRoute:
      AppOrganizationIdPropertyPropertyIdEditRoute,
  }

const AppOrganizationIdPropertyPropertyIdRouteWithChildren =
  AppOrganizationIdPropertyPropertyIdRoute._addFileChildren(
    AppOrganizationIdPropertyPropertyIdRouteChildren,
  )

interface AppOrganizationIdPropertyRouteRouteChildren {
  AppOrganizationIdPropertyPropertyIdRoute: typeof AppOrganizationIdPropertyPropertyIdRouteWithChildren
  AppOrganizationIdPropertyCreateRoute: typeof AppOrganizationIdPropertyCreateRoute
  AppOrganizationIdPropertyImportRoute: typeof AppOrganizationIdPropertyImportRoute
  AppOrganizationIdPropertyIndexRoute: typeof AppOrganizationIdPropertyIndexRoute
}

const AppOrganizationIdPropertyRouteRouteChildren: AppOrganizationIdPropertyRouteRouteChildren =
  {
    AppOrganizationIdPropertyPropertyIdRoute:
      AppOrganizationIdPropertyPropertyIdRouteWithChildren,
    AppOrganizationIdPropertyCreateRoute: AppOrganizationIdPropertyCreateRoute,
    AppOrganizationIdPropertyImportRoute: AppOrganizationIdPropertyImportRoute,
    AppOrganizationIdPropertyIndexRoute: AppOrganizationIdPropertyIndexRoute,
  }

const AppOrganizationIdPropertyRouteRouteWithChildren =
  AppOrganizationIdPropertyRouteRoute._addFileChildren(
    AppOrganizationIdPropertyRouteRouteChildren,
  )

interface AppOrganizationIdRouteRouteChildren {
  AppOrganizationIdPropertyRouteRoute: typeof AppOrganizationIdPropertyRouteRouteWithChildren
  AppOrganizationIdIndexRoute: typeof AppOrganizationIdIndexRoute
}

const AppOrganizationIdRouteRouteChildren: AppOrganizationIdRouteRouteChildren =
  {
    AppOrganizationIdPropertyRouteRoute:
      AppOrganizationIdPropertyRouteRouteWithChildren,
    AppOrganizationIdIndexRoute: AppOrganizationIdIndexRoute,
  }

const AppOrganizationIdRouteRouteWithChildren =
  AppOrganizationIdRouteRoute._addFileChildren(
    AppOrganizationIdRouteRouteChildren,
  )

interface AppuserAdminRouteRouteChildren {
  AppuserAdminIndexRoute: typeof AppuserAdminIndexRoute
  AppuserAdminOrganizationIdRoute: typeof AppuserAdminOrganizationIdRoute
  AppuserAdminOrganizationCreateRoute: typeof AppuserAdminOrganizationCreateRoute
  AppuserAdminOrganizationIndexRoute: typeof AppuserAdminOrganizationIndexRoute
}

const AppuserAdminRouteRouteChildren: AppuserAdminRouteRouteChildren = {
  AppuserAdminIndexRoute: AppuserAdminIndexRoute,
  AppuserAdminOrganizationIdRoute: AppuserAdminOrganizationIdRoute,
  AppuserAdminOrganizationCreateRoute: AppuserAdminOrganizationCreateRoute,
  AppuserAdminOrganizationIndexRoute: AppuserAdminOrganizationIndexRoute,
}

const AppuserAdminRouteRouteWithChildren =
  AppuserAdminRouteRoute._addFileChildren(AppuserAdminRouteRouteChildren)

interface AppuserRouteRouteChildren {
  AppuserAdminRouteRoute: typeof AppuserAdminRouteRouteWithChildren
  AppuserIndexRoute: typeof AppuserIndexRoute
  AppuserAccountIndexRoute: typeof AppuserAccountIndexRoute
}

const AppuserRouteRouteChildren: AppuserRouteRouteChildren = {
  AppuserAdminRouteRoute: AppuserAdminRouteRouteWithChildren,
  AppuserIndexRoute: AppuserIndexRoute,
  AppuserAccountIndexRoute: AppuserAccountIndexRoute,
}

const AppuserRouteRouteWithChildren = AppuserRouteRoute._addFileChildren(
  AppuserRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppOrganizationIdRouteRoute: typeof AppOrganizationIdRouteRouteWithChildren
  AppuserRouteRoute: typeof AppuserRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOrganizationIdRouteRoute: AppOrganizationIdRouteRouteWithChildren,
  AppuserRouteRoute: AppuserRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
