/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as AppAgencyIdRouteRouteImport } from './routes/app/$agencyId/route'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppAccountIndexRouteImport } from './routes/app/account/index'
import { Route as AppAgencyIdIndexRouteImport } from './routes/app/$agencyId/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppAdminOrganizationIndexRouteImport } from './routes/app/admin/organization/index'
import { Route as AppAgencyIdPropertyIndexRouteImport } from './routes/app/$agencyId/property/index'
import { Route as AppAdminOrganizationCreateRouteImport } from './routes/app/admin/organization/create'
import { Route as AppAdminOrganizationIdRouteImport } from './routes/app/admin/organization/$id'
import { Route as AppAgencyIdPropertyCreateRouteImport } from './routes/app/$agencyId/property/create'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgencyIdRouteRoute = AppAgencyIdRouteRouteImport.update({
  id: '/$agencyId',
  path: '/$agencyId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgencyIdIndexRoute = AppAgencyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgencyIdRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminOrganizationIndexRoute =
  AppAdminOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAgencyIdPropertyIndexRoute =
  AppAgencyIdPropertyIndexRouteImport.update({
    id: '/property/',
    path: '/property/',
    getParentRoute: () => AppAgencyIdRouteRoute,
  } as any)
const AppAdminOrganizationCreateRoute =
  AppAdminOrganizationCreateRouteImport.update({
    id: '/organization/create',
    path: '/organization/create',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminOrganizationIdRoute = AppAdminOrganizationIdRouteImport.update({
  id: '/organization/$id',
  path: '/organization/$id',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAgencyIdPropertyCreateRoute =
  AppAgencyIdPropertyCreateRouteImport.update({
    id: '/property/create',
    path: '/property/create',
    getParentRoute: () => AppAgencyIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/$agencyId': typeof AppAgencyIdRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$agencyId/': typeof AppAgencyIdIndexRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/$agencyId/property/create': typeof AppAgencyIdPropertyCreateRoute
  '/app/admin/organization/$id': typeof AppAdminOrganizationIdRoute
  '/app/admin/organization/create': typeof AppAdminOrganizationCreateRoute
  '/app/$agencyId/property/': typeof AppAgencyIdPropertyIndexRoute
  '/app/admin/organization/': typeof AppAdminOrganizationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$agencyId': typeof AppAgencyIdIndexRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/$agencyId/property/create': typeof AppAgencyIdPropertyCreateRoute
  '/app/admin/organization/$id': typeof AppAdminOrganizationIdRoute
  '/app/admin/organization/create': typeof AppAdminOrganizationCreateRoute
  '/app/$agencyId/property': typeof AppAgencyIdPropertyIndexRoute
  '/app/admin/organization': typeof AppAdminOrganizationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/$agencyId': typeof AppAgencyIdRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$agencyId/': typeof AppAgencyIdIndexRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/$agencyId/property/create': typeof AppAgencyIdPropertyCreateRoute
  '/app/admin/organization/$id': typeof AppAdminOrganizationIdRoute
  '/app/admin/organization/create': typeof AppAdminOrganizationCreateRoute
  '/app/$agencyId/property/': typeof AppAgencyIdPropertyIndexRoute
  '/app/admin/organization/': typeof AppAdminOrganizationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/$agencyId'
    | '/app/admin'
    | '/sign-in'
    | '/sign-up'
    | '/app/'
    | '/api/auth/$'
    | '/app/$agencyId/'
    | '/app/account/'
    | '/app/admin/'
    | '/app/$agencyId/property/create'
    | '/app/admin/organization/$id'
    | '/app/admin/organization/create'
    | '/app/$agencyId/property/'
    | '/app/admin/organization/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/app'
    | '/api/auth/$'
    | '/app/$agencyId'
    | '/app/account'
    | '/app/admin'
    | '/app/$agencyId/property/create'
    | '/app/admin/organization/$id'
    | '/app/admin/organization/create'
    | '/app/$agencyId/property'
    | '/app/admin/organization'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/app/$agencyId'
    | '/app/admin'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/app/'
    | '/api/auth/$'
    | '/app/$agencyId/'
    | '/app/account/'
    | '/app/admin/'
    | '/app/$agencyId/property/create'
    | '/app/admin/organization/$id'
    | '/app/admin/organization/create'
    | '/app/$agencyId/property/'
    | '/app/admin/organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$agencyId': {
      id: '/app/$agencyId'
      path: '/$agencyId'
      fullPath: '/app/$agencyId'
      preLoaderRoute: typeof AppAgencyIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/account'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$agencyId/': {
      id: '/app/$agencyId/'
      path: '/'
      fullPath: '/app/$agencyId/'
      preLoaderRoute: typeof AppAgencyIdIndexRouteImport
      parentRoute: typeof AppAgencyIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/organization/': {
      id: '/app/admin/organization/'
      path: '/organization'
      fullPath: '/app/admin/organization/'
      preLoaderRoute: typeof AppAdminOrganizationIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/$agencyId/property/': {
      id: '/app/$agencyId/property/'
      path: '/property'
      fullPath: '/app/$agencyId/property/'
      preLoaderRoute: typeof AppAgencyIdPropertyIndexRouteImport
      parentRoute: typeof AppAgencyIdRouteRoute
    }
    '/app/admin/organization/create': {
      id: '/app/admin/organization/create'
      path: '/organization/create'
      fullPath: '/app/admin/organization/create'
      preLoaderRoute: typeof AppAdminOrganizationCreateRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/organization/$id': {
      id: '/app/admin/organization/$id'
      path: '/organization/$id'
      fullPath: '/app/admin/organization/$id'
      preLoaderRoute: typeof AppAdminOrganizationIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/$agencyId/property/create': {
      id: '/app/$agencyId/property/create'
      path: '/property/create'
      fullPath: '/app/$agencyId/property/create'
      preLoaderRoute: typeof AppAgencyIdPropertyCreateRouteImport
      parentRoute: typeof AppAgencyIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AppAgencyIdRouteRouteChildren {
  AppAgencyIdIndexRoute: typeof AppAgencyIdIndexRoute
  AppAgencyIdPropertyCreateRoute: typeof AppAgencyIdPropertyCreateRoute
  AppAgencyIdPropertyIndexRoute: typeof AppAgencyIdPropertyIndexRoute
}

const AppAgencyIdRouteRouteChildren: AppAgencyIdRouteRouteChildren = {
  AppAgencyIdIndexRoute: AppAgencyIdIndexRoute,
  AppAgencyIdPropertyCreateRoute: AppAgencyIdPropertyCreateRoute,
  AppAgencyIdPropertyIndexRoute: AppAgencyIdPropertyIndexRoute,
}

const AppAgencyIdRouteRouteWithChildren =
  AppAgencyIdRouteRoute._addFileChildren(AppAgencyIdRouteRouteChildren)

interface AppAdminRouteRouteChildren {
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminOrganizationIdRoute: typeof AppAdminOrganizationIdRoute
  AppAdminOrganizationCreateRoute: typeof AppAdminOrganizationCreateRoute
  AppAdminOrganizationIndexRoute: typeof AppAdminOrganizationIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminOrganizationIdRoute: AppAdminOrganizationIdRoute,
  AppAdminOrganizationCreateRoute: AppAdminOrganizationCreateRoute,
  AppAdminOrganizationIndexRoute: AppAdminOrganizationIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAgencyIdRouteRoute: typeof AppAgencyIdRouteRouteWithChildren
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAgencyIdRouteRoute: AppAgencyIdRouteRouteWithChildren,
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
