/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AppDashboardRouteRouteImport } from './routes/app/dashboard/route'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppAccountIndexRouteImport } from './routes/app/account/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSOrganizationIdRouteRouteImport } from './routes/app/s/$organizationId/route'
import { Route as AppSOrganizationIdIndexRouteImport } from './routes/app/s/$organizationId/index'
import { Route as AppAdminOrganizationIndexRouteImport } from './routes/app/admin/organization/index'
import { Route as AppAdminOrganizationCreateRouteImport } from './routes/app/admin/organization/create'
import { Route as AppAdminOrganizationOrganizationIdRouteImport } from './routes/app/admin/organization/$organizationId'
import { Route as AppSOrganizationIdPropertyIndexRouteImport } from './routes/app/s/$organizationId/property/index'
import { Route as AppSOrganizationIdPropertyCreateRouteImport } from './routes/app/s/$organizationId/property/create'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRouteRoute = AppDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSOrganizationIdRouteRoute = AppSOrganizationIdRouteRouteImport.update({
  id: '/s/$organizationId',
  path: '/s/$organizationId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSOrganizationIdIndexRoute = AppSOrganizationIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSOrganizationIdRouteRoute,
} as any)
const AppAdminOrganizationIndexRoute =
  AppAdminOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminOrganizationCreateRoute =
  AppAdminOrganizationCreateRouteImport.update({
    id: '/organization/create',
    path: '/organization/create',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminOrganizationOrganizationIdRoute =
  AppAdminOrganizationOrganizationIdRouteImport.update({
    id: '/organization/$organizationId',
    path: '/organization/$organizationId',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppSOrganizationIdPropertyIndexRoute =
  AppSOrganizationIdPropertyIndexRouteImport.update({
    id: '/property/',
    path: '/property/',
    getParentRoute: () => AppSOrganizationIdRouteRoute,
  } as any)
const AppSOrganizationIdPropertyCreateRoute =
  AppSOrganizationIdPropertyCreateRouteImport.update({
    id: '/property/create',
    path: '/property/create',
    getParentRoute: () => AppSOrganizationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/app/': typeof AppIndexRoute
  '/app/s/$organizationId': typeof AppSOrganizationIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/admin/organization/$organizationId': typeof AppAdminOrganizationOrganizationIdRoute
  '/app/admin/organization/create': typeof AppAdminOrganizationCreateRoute
  '/app/admin/organization/': typeof AppAdminOrganizationIndexRoute
  '/app/s/$organizationId/': typeof AppSOrganizationIdIndexRoute
  '/app/s/$organizationId/property/create': typeof AppSOrganizationIdPropertyCreateRoute
  '/app/s/$organizationId/property/': typeof AppSOrganizationIdPropertyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/admin/organization/$organizationId': typeof AppAdminOrganizationOrganizationIdRoute
  '/app/admin/organization/create': typeof AppAdminOrganizationCreateRoute
  '/app/admin/organization': typeof AppAdminOrganizationIndexRoute
  '/app/s/$organizationId': typeof AppSOrganizationIdIndexRoute
  '/app/s/$organizationId/property/create': typeof AppSOrganizationIdPropertyCreateRoute
  '/app/s/$organizationId/property': typeof AppSOrganizationIdPropertyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/app/': typeof AppIndexRoute
  '/app/s/$organizationId': typeof AppSOrganizationIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/admin/organization/$organizationId': typeof AppAdminOrganizationOrganizationIdRoute
  '/app/admin/organization/create': typeof AppAdminOrganizationCreateRoute
  '/app/admin/organization/': typeof AppAdminOrganizationIndexRoute
  '/app/s/$organizationId/': typeof AppSOrganizationIdIndexRoute
  '/app/s/$organizationId/property/create': typeof AppSOrganizationIdPropertyCreateRoute
  '/app/s/$organizationId/property/': typeof AppSOrganizationIdPropertyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/app/'
    | '/app/s/$organizationId'
    | '/api/auth/$'
    | '/app/account/'
    | '/app/admin/'
    | '/app/dashboard/'
    | '/app/admin/organization/$organizationId'
    | '/app/admin/organization/create'
    | '/app/admin/organization/'
    | '/app/s/$organizationId/'
    | '/app/s/$organizationId/property/create'
    | '/app/s/$organizationId/property/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/app'
    | '/api/auth/$'
    | '/app/account'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/admin/organization/$organizationId'
    | '/app/admin/organization/create'
    | '/app/admin/organization'
    | '/app/s/$organizationId'
    | '/app/s/$organizationId/property/create'
    | '/app/s/$organizationId/property'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/dashboard'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/app/'
    | '/app/s/$organizationId'
    | '/api/auth/$'
    | '/app/account/'
    | '/app/admin/'
    | '/app/dashboard/'
    | '/app/admin/organization/$organizationId'
    | '/app/admin/organization/create'
    | '/app/admin/organization/'
    | '/app/s/$organizationId/'
    | '/app/s/$organizationId/property/create'
    | '/app/s/$organizationId/property/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/account'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/s/$organizationId': {
      id: '/app/s/$organizationId'
      path: '/s/$organizationId'
      fullPath: '/app/s/$organizationId'
      preLoaderRoute: typeof AppSOrganizationIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/s/$organizationId/': {
      id: '/app/s/$organizationId/'
      path: '/'
      fullPath: '/app/s/$organizationId/'
      preLoaderRoute: typeof AppSOrganizationIdIndexRouteImport
      parentRoute: typeof AppSOrganizationIdRouteRoute
    }
    '/app/admin/organization/': {
      id: '/app/admin/organization/'
      path: '/organization'
      fullPath: '/app/admin/organization/'
      preLoaderRoute: typeof AppAdminOrganizationIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/organization/create': {
      id: '/app/admin/organization/create'
      path: '/organization/create'
      fullPath: '/app/admin/organization/create'
      preLoaderRoute: typeof AppAdminOrganizationCreateRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/organization/$organizationId': {
      id: '/app/admin/organization/$organizationId'
      path: '/organization/$organizationId'
      fullPath: '/app/admin/organization/$organizationId'
      preLoaderRoute: typeof AppAdminOrganizationOrganizationIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/s/$organizationId/property/': {
      id: '/app/s/$organizationId/property/'
      path: '/property'
      fullPath: '/app/s/$organizationId/property/'
      preLoaderRoute: typeof AppSOrganizationIdPropertyIndexRouteImport
      parentRoute: typeof AppSOrganizationIdRouteRoute
    }
    '/app/s/$organizationId/property/create': {
      id: '/app/s/$organizationId/property/create'
      path: '/property/create'
      fullPath: '/app/s/$organizationId/property/create'
      preLoaderRoute: typeof AppSOrganizationIdPropertyCreateRouteImport
      parentRoute: typeof AppSOrganizationIdRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminOrganizationOrganizationIdRoute: typeof AppAdminOrganizationOrganizationIdRoute
  AppAdminOrganizationCreateRoute: typeof AppAdminOrganizationCreateRoute
  AppAdminOrganizationIndexRoute: typeof AppAdminOrganizationIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminOrganizationOrganizationIdRoute:
    AppAdminOrganizationOrganizationIdRoute,
  AppAdminOrganizationCreateRoute: AppAdminOrganizationCreateRoute,
  AppAdminOrganizationIndexRoute: AppAdminOrganizationIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppDashboardRouteRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteRouteChildren: AppDashboardRouteRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteRouteWithChildren =
  AppDashboardRouteRoute._addFileChildren(AppDashboardRouteRouteChildren)

interface AppSOrganizationIdRouteRouteChildren {
  AppSOrganizationIdIndexRoute: typeof AppSOrganizationIdIndexRoute
  AppSOrganizationIdPropertyCreateRoute: typeof AppSOrganizationIdPropertyCreateRoute
  AppSOrganizationIdPropertyIndexRoute: typeof AppSOrganizationIdPropertyIndexRoute
}

const AppSOrganizationIdRouteRouteChildren: AppSOrganizationIdRouteRouteChildren =
  {
    AppSOrganizationIdIndexRoute: AppSOrganizationIdIndexRoute,
    AppSOrganizationIdPropertyCreateRoute:
      AppSOrganizationIdPropertyCreateRoute,
    AppSOrganizationIdPropertyIndexRoute: AppSOrganizationIdPropertyIndexRoute,
  }

const AppSOrganizationIdRouteRouteWithChildren =
  AppSOrganizationIdRouteRoute._addFileChildren(
    AppSOrganizationIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppDashboardRouteRoute: typeof AppDashboardRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppSOrganizationIdRouteRoute: typeof AppSOrganizationIdRouteRouteWithChildren
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppDashboardRouteRoute: AppDashboardRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppSOrganizationIdRouteRoute: AppSOrganizationIdRouteRouteWithChildren,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
